Guide for setting up CP and deploy a sidecar
cyralinc/terraform-provider-cyral pull request #156
Opened 2022-02-03 03:49 UTC by wcmjunior

2022-02-03 03:53 UTC, day1118 approved these changes

2022-02-03 21:36 UTC, VictorGFM approved these changes
Looks great!

2022-02-03 23:48 UTC, arleyl requested changes

2022-02-03 23:48 UTC, arleyl commented on docs/guides/setup_cp_and_deploy_sidecar.md
> +        # Set the allowed CIDR block for database access to the sidecar
Suggest changing "to" to "through" like this: "Set the allowed CIDR block for database access through the sidecar"

2022-02-04 00:00 UTC, arleyl approved these changes

2022-02-04 00:03 UTC, merged